version: '1'

services:
	postgres:
		image: postgres:9.6
		container_name: postgres
		environment:
			POSTGRES_USER: core
			POSTGRES_PASSWORD: J5brHrAXFLQSif0K
			POSTGRES_DB: core

	core:
		build: .
		image: chamaconekt/core
		links:
		- postgres
		container_name: core
		depends_on:
			- postgres
		environment:

	nginx:
		image: nginx:1.11.11-alpine
		links:
			- core
		container_name: nginx
		command: nginx -g 'daemon off;' -c /etc/core-nginx/nginx.conf
		depends_on:
			- core
		ports:
			- 80:80
		volumes_from:
			- core

volumes:
	core-static-files:
		driver:local